api/v1/ui/urls.py
from django.conf.urls import url, include
from .views import UploadProgressDataView, UploadProgressCreateView


upload_progress_bar = [
    url(r'^$', UploadProgressDataView.as_view(), name='upload-progress-data'),
    url(r'^create/$', UploadProgressCreateView.as_view(), name='upload-progress-create'),
]

urlpatterns = [
    url(r'^upload-progress/', include(upload_progress_bar)),
]

hogwarts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from ui.views import (
    InstitutionRegistrationView, HomeView, SettingsView, TimetableView,
    CabinetsView, PeoplesView, PartnersView, MessagesView
)

urlpatterns = [
    url(r'^', include('authentication.urls')),
    url(r'^register/$', InstitutionRegistrationView.as_view(), name='registration_register'),
    url(r'^', include('registration.backends.hmac.urls')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^ui/', include('ui.urls', namespace='ui')),
]

# Application pages
pages = [
    url(r'^$', HomeView.as_view(), {'slug': 'home'}, name='home'),
    url(r'^settings/$', SettingsView.as_view(), {'slug': 'settings'}, name='settings'),
    url(r'^timetable/$', TimetableView.as_view(), {'slug': 'timetable'}, name='timetable'),
    url(r'^cabinets/$', CabinetsView.as_view(), {'slug': 'cabinets'}, name='cabinets'),
    url(r'^peoples/$', PeoplesView.as_view(), {'slug': 'peoples'}, name='peoples'),
    url(r'^partners/$', PartnersView.as_view(), {'slug': 'partners'}, name='partners'),
    url(r'^messages/$', MessagesView.as_view(), {'slug': 'messages'}, name='messages'),
]

# Application pages
urlpatterns += [
    url(r'^', include(pages, namespace='page')),
]

if settings.DEBUG:
    from django.contrib import admin
    urlpatterns += [
        url(r'^jet/', include('jet.urls', 'jet')),
        url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
        url(r'^channels-api/', include('channels_api.urls')),
        url(r'^admin/', admin.site.urls)
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]

ui/urls.py
from django.conf.urls import url, include
from ui.views import UploadProgressCreateView


upload_progress_bar = [
    url(r'^create/$', UploadProgressCreateView.as_view(), name='upload-progress-create'),
]

urlpatterns = [
    url(r'^upload-progress/', include(upload_progress_bar)),
]

api/v1/ui/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions
from django.core.cache import cache
from ipware.ip import get_ip
import uuid


class UploadProgressDataView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, format=None):
        progress_id = None
        if 'X-Progress-ID' in self.request.GET:
            progress_id = self.request.GET['X-Progress-ID']
        elif 'X-Progress-ID' in self.request.META:
            progress_id = self.request.META['X-Progress-ID']
        if progress_id:
            cache_key = '%s_%s' % (get_ip(request), progress_id)
            data = cache.get(cache_key)
            return Response(dict(data))
        return Response({
            'error': 'You must provide X-Progress-ID header or query param.'
        })


class UploadProgressCreateView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, format=None):
        data = {'progress_id': uuid.uuid4()}
        return Response(data)

ui/views.py
from django.views.generic import TemplateView
from registration.backends.hmac.views import RegistrationView
from core.models import EducationalInstitution
from core.forms import InstitutionRegistrationForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http.response import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import View
from django.conf import settings
import uuid

from messenger.models import Group


class UploadProgressCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if not settings.DEBUG and not self.request.is_ajax():
            raise PermissionDenied('Request must be ajax')
        progress_theme = self.request.GET.get('progress-theme')
        if progress_theme:
            progress_bar = render_to_string(
                'tags/progress-bar.html', {
                    'progress_id': uuid.uuid4(),
                    'progress_theme': progress_theme
                }
            )
            return JsonResponse({'progress_bar': progress_bar})
        return JsonResponse({
            'error': 'You must provide progress-theme query param.'
        })


class InstitutionRegistrationView(RegistrationView):
    template_name = 'registration/registration_form.html'
    email_body_template = 'registration/activation_email.txt'
    email_subject_template = 'registration/activation_email_subject.txt'
    form_class = InstitutionRegistrationForm

    def create_inactive_user(self, form):
        """
        Create the inactive user account and send an email containing
        activation instructions.

        """
        new_user = form.save(commit=False)
        new_user.is_active = False
        new_user.save()

        EducationalInstitution.create(
            model_name=form.get_institution_model_name(),
            user=new_user
        )

        self.send_activation_email(new_user)

        return new_user


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context


class TimetableView(LoginRequiredMixin, TemplateView):
    template_name = 'timetable.html'

    def get_context_data(self, **kwargs):
        context = super(TimetableView, self).get_context_data(**kwargs)
        return context


class CabinetsView(LoginRequiredMixin, TemplateView):
    template_name = 'cabinets.html'

    def get_context_data(self, **kwargs):
        context = super(CabinetsView, self).get_context_data(**kwargs)
        return context


class PeoplesView(LoginRequiredMixin, TemplateView):
    template_name = 'peoples.html'

    def get_context_data(self, **kwargs):
        context = super(PeoplesView, self).get_context_data(**kwargs)
        return context


class PartnersView(LoginRequiredMixin, TemplateView):
    template_name = 'partners.html'

    def get_context_data(self, **kwargs):
        context = super(PartnersView, self).get_context_data(**kwargs)
        return context


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'settings.html'

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        return context


class MessagesView(LoginRequiredMixin, TemplateView):
    template_name = 'messages.html'

    def get_context_data(self, **kwargs):
        context = super(MessagesView, self).get_context_data(**kwargs)
        current_group = Group.get_group_by_gid(gid=self.request.GET.get('group'), request=self.request)
        if current_group:
            membership = current_group.memberships.get(person=self.request.profile)
            context['draft'] = membership.draft_messages.first()
        context['current_group'] = current_group
        return context

ui/templates/ui/themes/default/navigation/main-navbar.html
<div class="navbar navbar-default navbar-fixed-top header-highlight">{% load static hogwarts_ui %}
    <div class="navbar-header">
        <a class="navbar-brand" href="/"><img src="{% static 'images/logo_light.png' %}" alt=""></a>
        <ul class="nav navbar-nav visible-xs-block">
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
            {% if slug in 'cabinets' %}
                <li><a class="sidebar-mobile-detached-toggle"><i class="icon-filter3"></i></a></li>
            {% endif %}
        </ul>
    </div>
    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
        </ul>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-bell2"></i>
                        <span class="visible-xs-inline-block position-right">Activity</span>
{#                        <span class="status-mark border-pink-300"></span>#}
                        <span class="badge bg-indigo-400 border-white">236</span>
                    </a>

                    <div class="dropdown-menu dropdown-content">
{#                        <div class="dropdown-content-heading">#}
{#                            Activity#}
{#                            <ul class="icons-list">#}
{#                                <li><a href="#"><i class="icon-menu7"></i></a></li>#}
{#                            </ul>#}
{#                        </div>#}

                        <ul class="media-list dropdown-content-body width-350">
                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-mention"></i></a>
                                </div>

                                <div class="media-body">
                                    <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
                                    <div class="media-annotation">4 minutes ago</div>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-pink-400 btn-rounded btn-icon btn-xs"><i class="icon-paperplane"></i></a>
                                </div>

                                <div class="media-body">
                                    Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
                                    <div class="media-annotation">36 minutes ago</div>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-blue btn-rounded btn-icon btn-xs"><i class="icon-plus3"></i></a>
                                </div>

                                <div class="media-body">
                                    <a href="#">Chris Arney</a> created a new <span class="text-semibold">Design</span> branch in <span class="text-semibold">Limitless</span> repository
                                    <div class="media-annotation">2 hours ago</div>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-purple-300 btn-rounded btn-icon btn-xs"><i class="icon-truck"></i></a>
                                </div>

                                <div class="media-body">
                                    Shipping cost to the Netherlands has been reduced, database updated
                                    <div class="media-annotation">Feb 8, 11:30</div>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-warning-400 btn-rounded btn-icon btn-xs"><i class="icon-bubble8"></i></a>
                                </div>

                                <div class="media-body">
                                    New review received on <a href="#">Server side integration</a> services
                                    <div class="media-annotation">Feb 2, 10:20</div>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <a href="#" class="btn bg-teal-400 btn-rounded btn-icon btn-xs"><i class="icon-spinner11"></i></a>
                                </div>

                                <div class="media-body">
                                    <strong>January, 2016</strong> - 1320 new users, 3284 orders, $49,390 revenue
                                    <div class="media-annotation">Feb 1, 05:46</div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-bubble8"></i>
                        <span class="visible-xs-inline-block position-right">Messages</span>
{#                        <span class="status-mark border-pink-300"></span>#}
                        <span class="badge bg-indigo-400 border-white">7</span>
                    </a>

                    <div class="dropdown-menu dropdown-content width-350">
{#                        <div class="dropdown-content-heading">#}
{#                            Messages#}
{#                            <ul class="icons-list">#}
{#                                <li><a href="#"><i class="icon-compose"></i></a></li>#}
{#                            </ul>#}
{#                        </div>#}

                        <ul class="media-list dropdown-content-body">
                            <li class="media">
                                <div class="media-left">
                                    {% thumbnail_ui profile 'photo_thumbnail_square' as im %}
                                        <img src="{{ im.url }}" class="img-circle img-sm" alt="">
                                    {% empty %}
                                        <img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-sm" alt="">
                                    {% endthumbnail_ui %}
                                    <span class="badge bg-danger-400 media-badge">5</span>
                                </div>

                                <div class="media-body">
                                    <a href="#" class="media-heading">
                                        <span class="text-semibold">James Alexander</span>
                                        <span class="media-annotation pull-right">04:58</span>
                                    </a>

                                    <span class="text-muted">who knows, maybe that would be the best thing for me...</span>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left">
                                    <img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-sm" alt="">
                                    <span class="badge bg-danger-400 media-badge">4</span>
                                </div>

                                <div class="media-body">
                                    <a href="#" class="media-heading">
                                        <span class="text-semibold">Margo Baker</span>
                                        <span class="media-annotation pull-right">12:16</span>
                                    </a>

                                    <span class="text-muted">That was something he was unable to do because...</span>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left"><img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-sm" alt=""></div>
                                <div class="media-body">
                                    <a href="#" class="media-heading">
                                        <span class="text-semibold">Jeremy Victorino</span>
                                        <span class="media-annotation pull-right">22:48</span>
                                    </a>

                                    <span class="text-muted">But that would be extremely strained and suspicious...</span>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left"><img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-sm" alt=""></div>
                                <div class="media-body">
                                    <a href="#" class="media-heading">
                                        <span class="text-semibold">Beatrix Diaz</span>
                                        <span class="media-annotation pull-right">Tue</span>
                                    </a>

                                    <span class="text-muted">What a strenuous career it is that I've chosen...</span>
                                </div>
                            </li>

                            <li class="media">
                                <div class="media-left"><img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-sm" alt=""></div>
                                <div class="media-body">
                                    <a href="#" class="media-heading">
                                        <span class="text-semibold">Richard Vango</span>
                                        <span class="media-annotation pull-right">Mon</span>
                                    </a>

                                    <span class="text-muted">Other travelling salesmen live a life of luxury...</span>
                                </div>
                            </li>
                        </ul>

                        <div class="dropdown-content-footer">
                            <a href="#" data-popup="tooltip" title="All messages"><i class="icon-menu display-block"></i></a>
                        </div>
                    </div>
                </li>
                <li class="dropdown dropdown-user">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        {% thumbnail_ui profile 'photo_thumbnail_square' as im %}
                            <img src="{{ im.url }}" alt="">
                        {% empty %}
                            <img src="{% static 'images/placeholder.jpg' %}" alt="">
                        {% endthumbnail_ui %}
                        <span>{{ profile.first_name }}</span>
                        <i class="caret"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="profile">
                            <a>
                                {% thumbnail_ui profile 'photo_thumbnail_square' as im %}
                                    <img src="{{ im.url }}" style="margin-top: 0;" alt="">
                                {% empty %}
                                    <img src="{% static 'images/placeholder.jpg' %}" style="margin-top: 0;" alt="">
                                {% endthumbnail_ui %}
                                <span style="padding-top: 7.5px; padding-bottom: 7.5px; display: inline-block;">{{ profile.first_name }}</span>
                            </a>
                        </li>
                        <li class="profile">
                            <a>
                                {% thumbnail_ui profile1 'photo_thumbnail_square' as im %}
                                    <img src="{{ im.url }}" style="margin-top: 0;" alt="">
                                {% empty %}
                                    <img src="{% static 'images/placeholder.jpg' %}" style="margin-top: 0;" alt="">
                                {% endthumbnail_ui %}
                                <span style="padding-top: 7.5px; padding-bottom: 7.5px; display: inline-block;">{{ profile.first_name }}</span>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'page:settings' %}"><i class="icon-cog5"></i> Account settings</a></li>
                        <li><a href="{% url 'auth_logout' %}"><i class="icon-switch2"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

ui/templates/ui/themes/default/navigation/main-navigation.html
<div class="sidebar-category sidebar-category-visible">
    <div class="category-content no-padding">
        <ul class="navigation navigation-main navigation-accordion">

            <!-- Main -->
            <li class="{% if slug == 'home' %}active{% endif %}"><a href="{% url 'page:home' %}"><i class="icon-home4"></i> <span>My Page</span></a></li>
            <li class="{% if slug == 'messages' %}active{% endif %}">
                <a href="{% url 'page:messages' %}"><i class="icon-bubbles2"></i> <span>Messages <span class="label bg-indigo-400">{% if not new_messages|length_is:0 %}{{ new_messages|length }}{% endif %}</span></span></a>
            </li>
            <li class="{% if slug == 'peoples' %}active{% endif %}"><a href="{% url 'page:peoples' %}"><i class="icon-users"></i> <span>Peoples</span></a></li>
            <li class="{% if slug == 'timetable' %}active{% endif %}"><a href="{% url 'page:timetable' %}"><i class="icon-calendar2"></i> <span>Timetable</span></a></li>
            <li class="{% if slug == 'cabinets' %}active{% endif %}"><a href="{% url 'page:cabinets' %}"><i class="icon-enter2"></i> <span>Cabinets</span></a></li>
            <li class="{% if slug == 'partners' %}active{% endif %}"><a href="{% url 'page:partners' %}"><i class="icon-user"></i> <span>Partners</span></a></li>
            <li><a href="#"><i class="icon-microscope"></i> <span>Specialties</span></a></li>
            <!-- /main -->

        </ul>
    </div>
</div>

ui/templates/ui/themes/default/navigation/main-sidebar.html
<div class="sidebar sidebar-main sidebar-fixed">{% load static hogwarts_ui %}
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user-material">
            <div class="category-content">
                <div class="sidebar-user-material-content">
                    <a href="#">
                        {% thumbnail_ui profile 'photo_thumbnail_square' as im %}
                            <img src="{{ im.url }}" class="img-circle img-responsive" alt="">
                        {% empty %}
                            <img src="{% static 'images/placeholder.jpg' %}" class="img-circle img-responsive" alt="">
                        {% endthumbnail_ui %}
                    </a>
                    <h6>{{ profile.last_name }} {{ profile.first_name }}</h6>
                    <span class="text-size-small">{{ institution.name }}</span>
                </div>

                <div class="sidebar-user-material-menu">
                    <a href="#user-nav" data-toggle="collapse"><span>My account</span> <i class="caret"></i></a>
                </div>
            </div>

            <div class="navigation-wrapper collapse" id="user-nav">
                <ul class="navigation">
                    <li><a href="{% url 'page:settings' %}"><i class="icon-cog5"></i> <span>Settings</span></a></li>
                    <li><a href="{% url 'auth_logout' %}"><i class="icon-switch2"></i> <span>Logout</span></a></li>
                </ul>
            </div>
        </div>
        <!-- /user menu -->

        <!-- Main navigation -->
        {% include 'navigation/main-navigation.html' %}
        <!-- /main navigation -->

    </div>
</div>